path: /Users/kalea/Desktop/skyeyez-ai/data # dataset root dir
train: images/train # train images (relative to 'path') 24 images
val: images/train # val images (relative to 'path') 24 images

# classes
names:
  0: serena williams
